apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 240323806449.dkr.ecr.eu-west-2.amazonaws.com/example:latest
        ports:
        - containerPort: 8080
